/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GameRouteImport } from './routes/game'
import { Route as CakeRouteImport } from './routes/cake'
import { Route as BirthdayRouteImport } from './routes/birthday'
import { Route as IndexRouteImport } from './routes/index'

const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const CakeRoute = CakeRouteImport.update({
  id: '/cake',
  path: '/cake',
  getParentRoute: () => rootRouteImport,
} as any)
const BirthdayRoute = BirthdayRouteImport.update({
  id: '/birthday',
  path: '/birthday',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/birthday': typeof BirthdayRoute
  '/cake': typeof CakeRoute
  '/game': typeof GameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/birthday': typeof BirthdayRoute
  '/cake': typeof CakeRoute
  '/game': typeof GameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/birthday': typeof BirthdayRoute
  '/cake': typeof CakeRoute
  '/game': typeof GameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/birthday' | '/cake' | '/game'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/birthday' | '/cake' | '/game'
  id: '__root__' | '/' | '/birthday' | '/cake' | '/game'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BirthdayRoute: typeof BirthdayRoute
  CakeRoute: typeof CakeRoute
  GameRoute: typeof GameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cake': {
      id: '/cake'
      path: '/cake'
      fullPath: '/cake'
      preLoaderRoute: typeof CakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/birthday': {
      id: '/birthday'
      path: '/birthday'
      fullPath: '/birthday'
      preLoaderRoute: typeof BirthdayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BirthdayRoute: BirthdayRoute,
  CakeRoute: CakeRoute,
  GameRoute: GameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
